package decompiler

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"retract/pkg/api"
)

type context struct {
	fn          api.Function
	locals      map[string]string
	args        map[string]string
	lastCompare string
	usesRAX     bool
	stackDepth  int
	maxStack    int
}

var memRE = regexp.MustCompile(`^\[(r|e)?bp([+-])0x([0-9a-fA-F]+)\]$`)

func Pseudocode(fn api.Function, ins []api.Instruction) string {
	selected := sliceFunction(fn, ins)
	ctx := &context{fn: fn, locals: map[string]string{}, args: map[string]string{}}
	lines := liftFunction(ctx, selected)

	var b strings.Builder
	fmt.Fprintf(&b, "/*\n")
	fmt.Fprintf(&b, " * Retract decompiler output for %s (%s-%s).\n", fn.Name, fn.Start, fn.End)
	fmt.Fprintf(&b, " * This is recovered C-like pseudocode from static disassembly; validate types and control flow manually.\n")
	if len(fn.Calls) > 0 {
		fmt.Fprintf(&b, " * Calls: %s\n", strings.Join(fn.Calls, ", "))
	}
	fmt.Fprintf(&b, " */\n")
	fmt.Fprintf(&b, "uint64_t %s(void) {\n", cident(fn.Name))
	writeDecls(&b, ctx)
	for _, line := range lines {
		if line.label {
			fmt.Fprintf(&b, "%s:\n", line.text)
			continue
		}
		fmt.Fprintf(&b, "    %s\n", line.text)
	}
	if ctx.usesRAX {
		b.WriteString("    return rax;\n")
	} else {
		b.WriteString("    return 0;\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func ReconstructC(r api.AnalysisReport) string {
	var b strings.Builder
	b.WriteString("/*\n")
	b.WriteString(" * C-like reconstruction generated by retract.\n")
	b.WriteString(" * It combines decoded instructions, recovered stack variables, branch labels, imports, CFG metadata, and heuristic type notes.\n")
	b.WriteString(" * This is not guaranteed compilable source and must be validated before vulnerability conclusions.\n")
	b.WriteString(" */\n\n")
	b.WriteString("#include <stdint.h>\n#include <stddef.h>\n\n")
	fmt.Fprintf(&b, "/* sample: %s */\n", r.Metadata.Filename)
	fmt.Fprintf(&b, "/* sha256: %s */\n", r.Metadata.SHA256)
	fmt.Fprintf(&b, "/* risk: %s (%d/100) */\n\n", r.RiskLevel, r.RiskScore)
	writeImportDecls(&b, r.Imports)
	writeTypeNotes(&b, r)
	for _, fn := range r.Functions {
		b.WriteString(Pseudocode(fn, r.Instructions))
		b.WriteByte('\n')
	}
	return b.String()
}

type liftedLine struct {
	text  string
	label bool
}

func liftFunction(ctx *context, ins []api.Instruction) []liftedLine {
	var out []liftedLine
	labels := labelSet(ins)
	for i, in := range ins {
		if labels[in.Address] {
			out = append(out, liftedLine{text: labelName(in.Address), label: true})
		}
		if isPrologue(in, i) || isEpilogue(in) {
			continue
		}
		stmt := liftInstruction(ctx, in)
		if stmt == "" {
			continue
		}
		out = append(out, liftedLine{text: stmt})
	}
	return out
}

func liftInstruction(ctx *context, in api.Instruction) string {
	switch in.Kind {
	case "call":
		return liftCall(ctx, in)
	case "branch":
		cond := condition(ctx, in.Mnemonic)
		return fmt.Sprintf("if (%s) goto %s; /* %s */", cond, labelName(in.Target), asm(in))
	case "jump":
		return fmt.Sprintf("goto %s; /* %s */", labelName(in.Target), asm(in))
	case "return":
		ctx.usesRAX = true
		return fmt.Sprintf("return rax; /* %s */", asm(in))
	}
	ops := operands(in.Operand)
	switch in.Mnemonic {
	case "mov":
		if len(ops) == 2 {
			return assign(ctx, ops[0], expr(ctx, ops[1]), asm(in))
		}
	case "lea":
		if len(ops) == 2 {
			return assign(ctx, ops[0], "&"+expr(ctx, ops[1]), asm(in))
		}
	case "push":
		ctx.stackDepth += wordSize(ctx)
		if ctx.stackDepth > ctx.maxStack {
			ctx.maxStack = ctx.stackDepth
		}
		return fmt.Sprintf("push(%s); /* %s */", expr(ctx, in.Operand), asm(in))
	case "pop":
		if ctx.stackDepth >= wordSize(ctx) {
			ctx.stackDepth -= wordSize(ctx)
		}
		return assign(ctx, in.Operand, "pop()", asm(in))
	case "add", "sub", "xor", "or", "and":
		if len(ops) == 2 {
			op := map[string]string{"add": "+=", "sub": "-=", "xor": "^=", "or": "|=", "and": "&="}[in.Mnemonic]
			return fmt.Sprintf("%s %s %s; /* %s */", lvalue(ctx, ops[0]), op, expr(ctx, ops[1]), asm(in))
		}
	case "imul":
		if len(ops) == 2 {
			return fmt.Sprintf("%s *= %s; /* %s */", lvalue(ctx, ops[0]), expr(ctx, ops[1]), asm(in))
		}
		if len(ops) == 3 {
			return assign(ctx, ops[0], fmt.Sprintf("%s * %s", expr(ctx, ops[1]), expr(ctx, ops[2])), asm(in))
		}
	case "inc", "dec":
		if len(ops) == 1 {
			op := "++"
			if in.Mnemonic == "dec" {
				op = "--"
			}
			return fmt.Sprintf("%s%s; /* %s */", lvalue(ctx, ops[0]), op, asm(in))
		}
	case "cmp":
		if len(ops) == 2 {
			ctx.lastCompare = fmt.Sprintf("%s ? %s", expr(ctx, ops[0]), expr(ctx, ops[1]))
			return fmt.Sprintf("/* compare %s with %s; %s */", expr(ctx, ops[0]), expr(ctx, ops[1]), asm(in))
		}
	case "test":
		if len(ops) == 2 {
			ctx.lastCompare = fmt.Sprintf("(%s & %s) ? 0", expr(ctx, ops[0]), expr(ctx, ops[1]))
			return fmt.Sprintf("/* test %s & %s; %s */", expr(ctx, ops[0]), expr(ctx, ops[1]), asm(in))
		}
	case "nop":
		return ""
	}
	if in.Mnemonic == "db" {
		return fmt.Sprintf("/* undecoded byte %s */", asm(in))
	}
	return fmt.Sprintf("/* %s */", asm(in))
}

func liftCall(ctx *context, in api.Instruction) string {
	name := callName(in.Target)
	args := callArgs(ctx)
	ctx.usesRAX = true
	if len(args) == 0 {
		return fmt.Sprintf("rax = %s(); /* %s */", name, asm(in))
	}
	return fmt.Sprintf("rax = %s(%s); /* %s */", name, strings.Join(args, ", "), asm(in))
}

func callArgs(ctx *context) []string {
	regs := []string{"rcx", "rdx", "r8", "r9"}
	if strings.Contains(ctx.fn.Start, "0x") {
		regs = []string{"rcx", "rdx", "r8", "r9"}
	}
	var out []string
	for _, r := range regs {
		out = append(out, r)
	}
	return out
}

func writeDecls(b *strings.Builder, ctx *context) {
	b.WriteString("    uint64_t rax = 0, rcx = 0, rdx = 0, rbx = 0, rsp = 0, rbp = 0, rsi = 0, rdi = 0, r8 = 0, r9 = 0;\n")
	if ctx.maxStack > 0 {
		fmt.Fprintf(b, "    uint8_t stack_%d[%d];\n", ctx.maxStack, ctx.maxStack)
	}
	for _, name := range sortedValues(ctx.args) {
		fmt.Fprintf(b, "    uint64_t %s = 0;\n", name)
	}
	for _, name := range sortedValues(ctx.locals) {
		fmt.Fprintf(b, "    uint64_t %s = 0;\n", name)
	}
	if len(ctx.args) > 0 || len(ctx.locals) > 0 || ctx.maxStack > 0 {
		b.WriteByte('\n')
	}
}

func writeImportDecls(b *strings.Builder, imports []api.ImportFunction) {
	if len(imports) == 0 {
		return
	}
	b.WriteString("/* Imports observed */\n")
	seen := map[string]bool{}
	for _, imp := range imports {
		name := imp.Name
		if name == "" {
			name = fmt.Sprintf("ordinal_%d", imp.Ordinal)
		}
		c := cident(name)
		if seen[c] {
			continue
		}
		seen[c] = true
		fmt.Fprintf(b, "extern uint64_t %s(); /* %s */\n", c, imp.DLL)
	}
	b.WriteByte('\n')
}

func writeTypeNotes(b *strings.Builder, r api.AnalysisReport) {
	if len(r.InferredTypes) == 0 && len(r.StructCandidates) == 0 && len(r.Vulnerabilities) == 0 {
		return
	}
	b.WriteString("/* Analyst notes */\n")
	for _, t := range r.InferredTypes {
		fmt.Fprintf(b, "/* type %s %s confidence=%s evidence=%s */\n", t.Kind, t.Name, t.Confidence, strings.Join(t.Evidence, "; "))
	}
	for _, s := range r.StructCandidates {
		fmt.Fprintf(b, "/* struct %s fields=%s confidence=%s */\n", s.Name, strings.Join(s.Fields, ", "), s.Confidence)
	}
	for _, v := range r.Vulnerabilities {
		fmt.Fprintf(b, "/* [%s] %s: %s -- %s */\n", v.Severity, v.ID, v.Title, v.Evidence)
	}
	b.WriteByte('\n')
}

func assign(ctx *context, dst, src, note string) string {
	return fmt.Sprintf("%s = %s; /* %s */", lvalue(ctx, dst), src, note)
}

func condition(ctx *context, mnemonic string) string {
	left, right := "flags", "0"
	if ctx.lastCompare != "" {
		parts := strings.Split(ctx.lastCompare, " ? ")
		if len(parts) == 2 {
			left, right = parts[0], parts[1]
		}
	}
	op := map[string]string{
		"je": "==", "jz": "==", "jne": "!=", "jnz": "!=", "ja": ">", "jnbe": ">",
		"jae": ">=", "jnb": ">=", "jb": "<", "jnae": "<", "jbe": "<=", "jna": "<=",
		"jg": ">", "jnle": ">", "jge": ">=", "jnl": ">=", "jl": "<", "jnge": "<",
		"jle": "<=", "jng": "<=", "js": "< 0 &&", "jns": ">= 0 &&", "jo": "overflow",
		"jno": "!overflow", "jp": "parity", "jnp": "!parity",
	}[mnemonic]
	if op == "" {
		op = "!="
	}
	switch op {
	case "overflow", "!overflow", "parity", "!parity":
		return op
	case "< 0 &&", ">= 0 &&":
		return fmt.Sprintf("%s %s true", left, op)
	default:
		return fmt.Sprintf("%s %s %s", left, op, right)
	}
}

func expr(ctx *context, op string) string {
	op = strings.TrimSpace(op)
	if op == "" {
		return ""
	}
	if v := stackName(ctx, op); v != "" {
		return v
	}
	if strings.HasPrefix(op, "[") && strings.HasSuffix(op, "]") {
		return "*(" + expr(ctx, strings.TrimSuffix(strings.TrimPrefix(op, "["), "]")) + ")"
	}
	return cidentOperand(op)
}

func lvalue(ctx *context, op string) string {
	if v := stackName(ctx, op); v != "" {
		return v
	}
	return cidentOperand(op)
}

func stackName(ctx *context, op string) string {
	op = strings.ReplaceAll(strings.TrimSpace(op), " ", "")
	m := memRE.FindStringSubmatch(op)
	if len(m) == 0 {
		return ""
	}
	off, _ := strconv.ParseUint(m[3], 16, 64)
	if m[2] == "-" {
		name := fmt.Sprintf("local_%x", off)
		ctx.locals[op] = name
		return name
	}
	name := fmt.Sprintf("arg_%x", off)
	ctx.args[op] = name
	return name
}

func operands(s string) []string {
	if strings.TrimSpace(s) == "" {
		return nil
	}
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		out = append(out, strings.TrimSpace(p))
	}
	return out
}

func labelSet(ins []api.Instruction) map[string]bool {
	out := map[string]bool{}
	for _, in := range ins {
		if in.Target != "" && (in.Kind == "branch" || in.Kind == "jump") {
			out[in.Target] = true
		}
	}
	return out
}

func isPrologue(in api.Instruction, idx int) bool {
	if idx >= 3 {
		return false
	}
	return in.Mnemonic == "push" && (in.Operand == "rbp" || in.Operand == "ebp") ||
		in.Mnemonic == "mov" && (in.Operand == "rbp, rsp" || in.Operand == "ebp, esp")
}

func isEpilogue(in api.Instruction) bool {
	return in.Mnemonic == "pop" && (in.Operand == "rbp" || in.Operand == "ebp")
}

func wordSize(ctx *context) int {
	if strings.HasPrefix(ctx.fn.Start, "0x") {
		return 8
	}
	return 4
}

func sliceFunction(fn api.Function, ins []api.Instruction) []api.Instruction {
	start, ok1 := parseAddr(fn.Start)
	end, ok2 := parseAddr(fn.End)
	if !ok1 || !ok2 || end < start {
		return ins
	}
	out := []api.Instruction{}
	for _, in := range ins {
		addr, ok := parseAddr(in.Address)
		if ok && addr >= start && addr <= end {
			out = append(out, in)
		}
	}
	if len(out) == 0 {
		return ins
	}
	return out
}

func asm(in api.Instruction) string {
	if in.Operand == "" {
		return in.Address + ": " + in.Mnemonic
	}
	return in.Address + ": " + in.Mnemonic + " " + in.Operand
}

func parseAddr(s string) (uint64, bool) {
	v, err := strconv.ParseUint(strings.TrimPrefix(s, "0x"), 16, 64)
	return v, err == nil
}

func labelName(addr string) string {
	return "loc_" + strings.TrimPrefix(addr, "0x")
}

func callName(target string) string {
	if target == "" {
		return "indirect_call"
	}
	if strings.HasPrefix(target, "0x") {
		return "sub_" + strings.TrimPrefix(target, "0x")
	}
	return cident(target)
}

func sanitize(s string) string {
	return cident(s)
}

func cident(s string) string {
	if s == "" {
		return "unknown"
	}
	var b strings.Builder
	for i, r := range s {
		ok := r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_'
		if !ok {
			r = '_'
		}
		if i == 0 && r >= '0' && r <= '9' {
			b.WriteByte('_')
		}
		b.WriteRune(r)
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "unknown"
	}
	return out
}

func cidentOperand(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, "0x") {
		return s
	}
	return cident(s)
}

func sortedValues(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for _, v := range m {
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}
