package decompiler

import (
	"fmt"
	"strconv"
	"strings"

	"retract/pkg/api"
)

func Pseudocode(fn api.Function, ins []api.Instruction) string {
	var b strings.Builder
	fmt.Fprintf(&b, "/* Approximate pseudocode generated by retract. Verify manually. */\n")
	fmt.Fprintf(&b, "uint64_t %s(void) {\n", sanitize(fn.Name))
	b.WriteString("    uint64_t rax = 0, rcx = 0, rdx = 0, rbx = 0, rsp = 0, rbp = 0, rsi = 0, rdi = 0;\n")
	for _, in := range sliceFunction(fn, ins) {
		fmt.Fprintf(&b, "loc_%s:\n", strings.TrimPrefix(in.Address, "0x"))
		switch in.Kind {
		case "call":
			fmt.Fprintf(&b, "    call_%s(); /* %s */\n", strings.TrimPrefix(in.Target, "0x"), asm(in))
		case "branch":
			fmt.Fprintf(&b, "    if (condition_%s()) goto loc_%s; /* %s */\n", strings.TrimPrefix(in.Address, "0x"), strings.TrimPrefix(in.Target, "0x"), asm(in))
		case "jump":
			fmt.Fprintf(&b, "    goto loc_%s; /* %s */\n", strings.TrimPrefix(in.Target, "0x"), asm(in))
		case "return":
			b.WriteString("    return rax;\n")
		default:
			if stmt := lift(in); stmt != "" {
				fmt.Fprintf(&b, "    %s /* %s */\n", stmt, asm(in))
			} else {
				fmt.Fprintf(&b, "    /* %s */\n", asm(in))
			}
		}
	}
	b.WriteString("    return rax;\n")
	b.WriteString("}\n")
	return b.String()
}

func ReconstructC(r api.AnalysisReport) string {
	var b strings.Builder
	b.WriteString("/*\n")
	b.WriteString(" * Approximate C reconstruction generated by retract.\n")
	b.WriteString(" * This is static-analysis guidance, not compilable recovered source.\n")
	b.WriteString(" * Verify all control flow, types, calling conventions, and data references manually.\n")
	b.WriteString(" */\n\n")
	b.WriteString("#include <stdint.h>\n#include <stddef.h>\n\n")
	fmt.Fprintf(&b, "/* sample: %s */\n", r.Metadata.Filename)
	fmt.Fprintf(&b, "/* sha256: %s */\n", r.Metadata.SHA256)
	fmt.Fprintf(&b, "/* risk: %s (%d/100) */\n\n", r.RiskLevel, r.RiskScore)
	if len(r.Imports) > 0 {
		b.WriteString("/* Imports observed */\n")
		for _, imp := range r.Imports {
			name := imp.Name
			if name == "" {
				name = fmt.Sprintf("ordinal_%d", imp.Ordinal)
			}
			fmt.Fprintf(&b, "extern uint64_t %s(); /* %s */\n", cident(name), imp.DLL)
		}
		b.WriteByte('\n')
	}
	if len(r.Vulnerabilities) > 0 {
		b.WriteString("/* Vulnerability review notes */\n")
		for _, v := range r.Vulnerabilities {
			fmt.Fprintf(&b, "/* [%s] %s: %s -- %s */\n", v.Severity, v.ID, v.Title, v.Evidence)
		}
		b.WriteByte('\n')
	}
	for _, fn := range r.Functions {
		b.WriteString(Pseudocode(fn, r.Instructions))
		b.WriteByte('\n')
	}
	return b.String()
}

func sanitize(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	if s == "" {
		return "sub_unknown"
	}
	return s
}

func sliceFunction(fn api.Function, ins []api.Instruction) []api.Instruction {
	start, ok1 := parseAddr(fn.Start)
	end, ok2 := parseAddr(fn.End)
	if !ok1 || !ok2 || end < start {
		return ins
	}
	out := []api.Instruction{}
	for _, in := range ins {
		addr, ok := parseAddr(in.Address)
		if ok && addr >= start && addr <= end {
			out = append(out, in)
		}
	}
	if len(out) == 0 {
		return ins
	}
	return out
}

func lift(in api.Instruction) string {
	switch in.Mnemonic {
	case "mov":
		parts := strings.SplitN(in.Operand, ",", 2)
		if len(parts) == 2 {
			return strings.TrimSpace(parts[0]) + " = " + strings.TrimSpace(parts[1]) + ";"
		}
	case "push":
		return "push(" + in.Operand + ");"
	case "pop":
		return in.Operand + " = pop();"
	case "sub", "add", "xor", "or", "and":
		parts := strings.SplitN(in.Operand, ",", 2)
		if len(parts) == 2 {
			op := map[string]string{"sub": "-=", "add": "+=", "xor": "^=", "or": "|=", "and": "&="}[in.Mnemonic]
			return strings.TrimSpace(parts[0]) + " " + op + " " + strings.TrimSpace(parts[1]) + ";"
		}
	case "nop":
		return ""
	}
	return ""
}

func asm(in api.Instruction) string {
	if in.Operand == "" {
		return in.Address + ": " + in.Mnemonic
	}
	return in.Address + ": " + in.Mnemonic + " " + in.Operand
}

func parseAddr(s string) (uint64, bool) {
	v, err := strconv.ParseUint(strings.TrimPrefix(s, "0x"), 16, 64)
	return v, err == nil
}

func cident(s string) string {
	if s == "" {
		return "unknown_import"
	}
	var b strings.Builder
	for i, r := range s {
		ok := r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_'
		if !ok {
			r = '_'
		}
		if i == 0 && r >= '0' && r <= '9' {
			b.WriteByte('_')
		}
		b.WriteRune(r)
	}
	return b.String()
}
